### ISSUE TITLE
The demo is not accessible

### ISSUE THREAD

**Issue by lichen14** [halleewong/ScribblePrompt#2]
GREAT WORK!!!

I found that the demo (https://huggingface.co/spaces/halleewong/ScribblePrompt) was not accessible.
Could you please update it?

BTW, I have no idea if the ScribblePrompt has interactive UI with users? just like annotators.   :D

**Comment by halleewong** [comment]
Hi, the demo is accessible and currently working for me. Are you still having trouble accessing it?

**Comment by lichen14** [comment]
Thanks for your reply :D
Unfortunately, I just tried to access the demo but failed. 
Is there any limitation?

**Comment by halleewong** [comment]
It seems that Hugging Face Spaces, where the demo is hosted, is blocked in China.

I've added the demo code to `./demos` so you can run the app locally. Hope this helps!

**Comment by lichen14** [comment]
wow! cool
I'll give it a try!   :D
